#include <stdio.h>

int main(){


    int result = 0;
    int result1 = 0;
   
    result = 0+1;
    printf("%d\n", result);
    result1 = result+1;
    printf("%d\n", result1);
    result = result+result1;
    printf("%d\n", result);
    result1 = result+result1;
    printf("%d\n", result1);
    result = result+result1;
    printf("%d\n", result);
    result1 = result+result1;
    printf("%d\n", result1);
    result = result+result1;
    printf("%d\n", result);
    result1 = result+result1;
    printf("%d\n", result1);
    result = result+result1;
    printf("%d\n", result);
    result1 = result+result1;
    printf("%d\n", result1);
    result = result+result1;
    printf("%d\n", result);
    result1 = result+result1;
    printf("%d\n", result1);
    result = result+result1;
    printf("%d\n", result);
    result1 = result+result1;
    printf("%d\n", result1);
    result = result+result1;
    printf("%d\n", result);
    result1 = result+result1;
    printf("%d\n", result1);
    result = result+result1;
    printf("%d\n", result);
    result1 = result+result1;
    printf("%d\n", result1);
    result = result+result1;
    printf("%d\n", result);
    result1 = result+result1;
    printf("%d\n", result1);
    result = result+result1;
    printf("%d\n", result);
    result1 = result+result1;
    printf("%d\n", result1);
    result = result+result1;
    printf("%d\n", result);
    result1 = result+result1;
    printf("%d\n", result1);
    result = result+result1;
    printf("%d\n", result);
    result1 = result+result1;
    printf("%d\n", result1);
    result = result+result1;
    printf("%d\n", result);
    result1 = result+result1;
    printf("%d\n", result1);
    result = result+result1;
    printf("%d\n", result);
    result1 = result+result1;
    printf("%d\n", result1);
    result = result+result1;
    printf("%d\n", result);
    result1 = result+result1;
    printf("%d\n", result1);
    result = result+result1;
    printf("%d\n", result);
    result1 = result+result1;
    printf("%d\n", result1);
    result = result+result1;
    printf("%d\n", result);
    result1 = result+result1;
    printf("%d\n", result1);
    result = result+result1;
    printf("%d\n", result);
    result1 = result+result1;
    printf("%d\n", result1);
    result = result+result1;
    printf("%d\n", result);
    result1 = result+result1;
    printf("%d\n", result1);
    result = result+result1;
    printf("%d\n", result);
    result1 = result+result1;
    printf("%d\n", result1);
    result = result+result1;
    printf("%d\n", result);
    result1 = result+result1;
    printf("%d\n", result1);
    result = result+result1;
    printf("%d\n", result);
    result1 = result+result1;
    printf("%d\n", result1);
    result = result+result1;
    printf("%d\n", result);
    result1 = result+result1;
    printf("%d\n", result1);
    result = result+result1;
    printf("%d\n", result);
    result1 = result+result1;
    printf("%d\n", result1);
    result = result+result1;
    printf("%d\n", result);
    result1 = result+result1;
    printf("%d\n", result1);
    result = result+result1;
    printf("%d\n", result);
    result1 = result+result1;
    printf("%d\n", result1);
    result = result+result1;
    printf("%d\n", result);
    result1 = result+result1;
    printf("%d\n", result1);
    result = result+result1;
    printf("%d\n", result);
    result1 = result+result1;
    printf("%d\n", result1);
    result = result+result1;
    printf("%d\n", result);
    result1 = result+result1;
    printf("%d\n", result1);
    result = result+result1;
    printf("%d\n", result);
    result1 = result+result1;
    printf("%d\n", result1);
    result = result+result1;
    printf("%d\n", result);
    result1 = result+result1;
    printf("%d\n", result1);
    result = result+result1;
    printf("%d\n", result);
    result1 = result+result1;
    printf("%d\n", result1);
    result = result+result1;
    printf("%d\n", result);
    result1 = result+result1;
    printf("%d\n", result1);
    result = result+result1;
    printf("%d\n", result);
    result1 = result+result1;
    printf("%d\n", result1);
    result = result+result1;
    printf("%d\n", result);
    result1 = result+result1;
    printf("%d\n", result1);
    result = result+result1;
    printf("%d\n", result);
    result1 = result+result1;
    printf("%d\n", result1);
    result = result+result1;
    printf("%d\n", result);
    result1 = result+result1;
    printf("%d\n", result1);
    result = result+result1;
    printf("%d\n", result);
    result1 = result+result1;
    printf("%d\n", result1);
    result = result+result1;
    printf("%d\n", result);
    result1 = result+result1;
    printf("%d\n", result1);
    result = result+result1;
    printf("%d\n", result);
    result1 = result+result1;
    printf("%d\n", result1);
    result = result+result1;
    printf("%d\n", result);
    result1 = result+result1;
    printf("%d\n", result1);
    result = result+result1;
    printf("%d\n", result);
    result1 = result+result1;
    printf("%d\n", result1);
    result = result+result1;
    printf("%d\n", result);
    result1 = result+result1;
    printf("%d\n", result1);
    result = result+result1;
    printf("%d\n", result);
    result1 = result+result1;
    printf("%d\n", result1);
    result = result+result1;
    printf("%d\n", result);
    result1 = result+result1;
    printf("%d\n", result1);
    result = result+result1;
    printf("%d\n", result);
    result1 = result+result1;
    printf("%d\n", result1);
    result = result+result1;
    printf("%d\n", result);
    result1 = result+result1;
    printf("%d\n", result1);
    result = result+result1;
    printf("%d\n", result);
    result1 = result+result1;
    printf("%d\n", result1);
    result = result+result1;
    printf("%d\n", result);
    result1 = result+result1;
    printf("%d\n", result1);
    result = result+result1;
    printf("%d\n", result);
    result1 = result+result1;
    printf("%d\n", result1);
    result = result+result1;
    printf("%d\n", result);
    result1 = result+result1;
    printf("%d\n", result1);
    result = result+result1;
    printf("%d\n", result);
    result1 = result+result1;
    printf("%d\n", result1);
    result = result+result1;
    printf("%d\n", result);
    result1 = result+result1;
    printf("%d\n", result1);
    result = result+result1;
    printf("%d\n", result);
    result1 = result+result1;
    printf("%d\n", result1);
    result = result+result1;
    printf("%d\n", result);
    result1 = result+result1;
    printf("%d\n", result1);
    result = result+result1;
    printf("%d\n", result);
    result1 = result+result1;
    printf("%d\n", result1);
    result = result+result1;
    printf("%d\n", result);
    result1 = result+result1;
    printf("%d\n", result1);
    result = result+result1;
    printf("%d\n", result);
    result1 = result+result1;
    printf("%d\n", result1);
    result = result+result1;
    printf("%d\n", result);
    result1 = result+result1;
    printf("%d\n", result1);
    result = result+result1;
    printf("%d\n", result);
    result1 = result+result1;
    printf("%d\n", result1);
    result = result+result1;
    printf("%d\n", result);
    result1 = result+result1;
    printf("%d\n", result1);
    result = result+result1;
    printf("%d\n", result);
    result1 = result+result1;
    printf("%d\n", result1);
    result = result+result1;
    printf("%d\n", result);
    result1 = result+result1;
    printf("%d\n", result1);
    result = result+result1;
    printf("%d\n", result);
    result1 = result+result1;
    printf("%d\n", result1);
    result = result+result1;
    printf("%d\n", result);
    result1 = result+result1;
    printf("%d\n", result1);
    result = result+result1;
    printf("%d\n", result);
    result1 = result+result1;
    printf("%d\n", result1);
    result = result+result1;
    printf("%d\n", result);
    result1 = result+result1;
    printf("%d\n", result1);
    result = result+result1;
    printf("%d\n", result);
    result1 = result+result1;
    printf("%d\n", result1);
    result = result+result1;
    printf("%d\n", result);
    result1 = result+result1;
    printf("%d\n", result1);
    result = result+result1;
    printf("%d\n", result);
    result1 = result+result1;
    printf("%d\n", result1);
    result = result+result1;
    printf("%d\n", result);
    result1 = result+result1;
    printf("%d\n", result1);
    result = result+result1;
    printf("%d\n", result);
    result1 = result+result1;
    printf("%d\n", result1);
    result = result+result1;
    printf("%d\n", result);
    result1 = result+result1;
    printf("%d\n", result1);
    result = result+result1;
    printf("%d\n", result);
    result1 = result+result1;
    printf("%d\n", result1);
    result = result+result1;
    printf("%d\n", result);
    result1 = result+result1;
    printf("%d\n", result1);
    result = result+result1;
    printf("%d\n", result);
    result1 = result+result1;
    printf("%d\n", result1);
    result = result+result1;
    printf("%d\n", result);
    result1 = result+result1;
    printf("%d\n", result1);
    result = result+result1;
    printf("%d\n", result);
    result1 = result+result1;
    printf("%d\n", result1);
    result = result+result1;
    printf("%d\n", result);
    result1 = result+result1;
    printf("%d\n", result1);
    result = result+result1;
    printf("%d\n", result);
    result1 = result+result1;
    printf("%d\n", result1);
    result = result+result1;
    printf("%d\n", result);
    result1 = result+result1;
    printf("%d\n", result1);
    result = result+result1;
    printf("%d\n", result);
    result1 = result+result1;
    printf("%d\n", result1);
    result = result+result1;
    printf("%d\n", result);
    result1 = result+result1;
    printf("%d\n", result1);
    result = result+result1;
    printf("%d\n", result);
    result1 = result+result1;
    printf("%d\n", result1);
    result = result+result1;
    printf("%d\n", result);
    result1 = result+result1;
    printf("%d\n", result1);
    result = result+result1;
    printf("%d\n", result);
    result1 = result+result1;
    printf("%d\n", result1);
    result = result+result1;
    printf("%d\n", result);
    result1 = result+result1;
    printf("%d\n", result1);
    result = result+result1;
    printf("%d\n", result);
    result1 = result+result1;
    printf("%d\n", result1);
    result = result+result1;
    printf("%d\n", result);
    result1 = result+result1;
    printf("%d\n", result1);
    result = result+result1;
    printf("%d\n", result);
    result1 = result+result1;
    printf("%d\n", result1);
    result = result+result1;
    printf("%d\n", result);
    result1 = result+result1;
    printf("%d\n", result1);
    result = result+result1;
    printf("%d\n", result);
    result1 = result+result1;
    printf("%d\n", result1);
    result = result+result1;
    printf("%d\n", result);
    result1 = result+result1;
    printf("%d\n", result1);
    result = result+result1;
    printf("%d\n", result);
    result1 = result+result1;
    printf("%d\n", result1);
    result = result+result1;
    printf("%d\n", result);
    result1 = result+result1;
    printf("%d\n", result1);
    result = result+result1;
    printf("%d\n", result);
    result1 = result+result1;
    printf("%d\n", result1);
    result = result+result1;
    printf("%d\n", result);
    result1 = result+result1;
    printf("%d\n", result1);
    result = result+result1;
    printf("%d\n", result);
    result1 = result+result1;
    printf("%d\n", result1);
    result = result+result1;
    printf("%d\n", result);
    result1 = result+result1;
    printf("%d\n", result1);
    result = result+result1;
    printf("%d\n", result);
    result1 = result+result1;
    printf("%d\n", result1);
    result = result+result1;
    printf("%d\n", result);
    result1 = result+result1;
    printf("%d\n", result1);
    result = result+result1;
    printf("%d\n", result);
    result1 = result+result1;
    printf("%d\n", result1);

     
}